name: partA_flow

# learning hyperparameters
batch_size: 128
epochs: 20
lr: 0.001

#Model
model: VAE
latent_dim: 2
prior: FlowPrior
encoder: GaussianEncoder
decoder: BernoulliDecoder
encoder_decoder_nets: LinearEncoderDecoderNets


# Data
transform_description: binarized

