name: partB_VAE

# learning hyperparameters
batch_size: 128
epochs: 50
lr: 0.001

#Model
model: VAE
latent_dim: 2
prior: VampPrior
encoder: GaussianEncoder
decoder: ContinuesBernoulliDecoder
encoder_decoder_nets: LinearEncoderDecoderNets


# Data
transform_description: flatten
dim: 784
