name: partB_flow

# learning hyperparameters
batch_size: 128
epochs: 10
lr: 0.001

#Model
model: MNISTFlow
num_transformations: 20
num_hidden: 256
masking: checkerboard


# Data
dim: 784
transform_description: dequantized

