name: partB_ddpm

# learning hyperparameters
batch_size: 128
epochs: 100
lr: 0.001

#Model
model: DDPM
network: Unet
T: 1000
beta_1: 0.0001
beta_T: 0.02


# Data
dim: 784
transform_description: minus_one_to_one

